// Catálogo de cenários. É a fonte única: o dashboard e a suíte de CI leem daqui.
// expectedFailures = validações que DEVEM falhar. Se falharem, o validador está funcionando.
const ALL = ['pagamento.iniciar', 'pagamento.autorizar', 'pagamento.confirmar'];
const UNTIL_AUTH = ['pagamento.iniciar', 'pagamento.autorizar'];

module.exports = [
  {
    id: 'aprovado',
    nome: 'Cartão aprovado',
    grupo: 'Caminho feliz',
    metodo: 'credit_card',
    descricao: 'Jornada completa: iniciar → autorizar → confirmar.',
    objetivo: 'Linha de base: todas as validações devem passar.',
    expectedStages: ALL,
    expectedOutcome: { technical: 'success', business: 'approved' },
    expectedFailures: [],
  },
  {
    id: 'pix_pendente',
    nome: 'PIX pendente',
    grupo: 'Negócio',
    metodo: 'pix',
    descricao: 'Adquirente devolve "pendente". A jornada para na autorização.',
    objetivo: 'Pendente não é erro: technical=success, business=pending.',
    expectedStages: UNTIL_AUTH,
    expectedOutcome: { technical: 'success', business: 'pending' },
    expectedFailures: [],
  },
  {
    id: 'recusado',
    nome: 'Cartão recusado',
    grupo: 'Negócio',
    metodo: 'credit_card',
    descricao: 'Adquirente recusa por saldo insuficiente (HTTP 200).',
    objetivo: 'Recusa de negócio NÃO pode contar como falha técnica.',
    expectedStages: UNTIL_AUTH,
    expectedOutcome: { technical: 'success', business: 'declined' },
    expectedFailures: [],
  },
  {
    id: 'timeout_adquirente',
    nome: 'Timeout no adquirente',
    grupo: 'Técnico',
    metodo: 'credit_card',
    descricao: 'Adquirente demora 3s; payment-service corta em 2s e devolve 504.',
    objetivo: 'Classificar como timeout e estourar o limite de latência.',
    expectedStages: UNTIL_AUTH,
    expectedOutcome: { technical: 'timeout', business: 'none' },
    expectedFailures: ['latencia'],
  },
  {
    id: 'erro_adquirente',
    nome: 'Erro 5xx no adquirente',
    grupo: 'Técnico',
    metodo: 'credit_card',
    descricao: 'Adquirente responde 500; BFF devolve 502.',
    objetivo: 'Classificar como dependency_error, não como recusa.',
    expectedStages: UNTIL_AUTH,
    expectedOutcome: { technical: 'dependency_error', business: 'none' },
    expectedFailures: [],
  },
  {
    id: 'lentidao',
    nome: 'Lentidão na autorização',
    grupo: 'Técnico',
    metodo: 'credit_card',
    descricao: 'Aprova, mas o adquirente leva ~1,4s.',
    objetivo: 'Sucesso com latência acima do limite deve ser sinalizado.',
    expectedStages: ALL,
    expectedOutcome: { technical: 'success', business: 'approved' },
    expectedFailures: ['latencia'],
  },
  {
    id: 'quebra_correlacao',
    nome: 'Quebra de correlação',
    grupo: 'Observabilidade',
    metodo: 'credit_card',
    descricao: 'payment-service chama o adquirente sem propagar trace nem correlation-id.',
    objetivo: 'Provar que o validador detecta onde o trace.id se perde.',
    expectedStages: ALL,
    expectedOutcome: { technical: 'success', business: 'approved' },
    expectedFailures: ['correlacao.trace', 'correlacao.id'],
  },
  {
    id: 'vazamento_pan',
    nome: 'Vazamento de PAN em log',
    grupo: 'Observabilidade',
    metodo: 'credit_card',
    descricao: 'payment-service registra o cartão sem mascarar (logger inseguro).',
    objetivo: 'Provar que a varredura de dados sensíveis bloqueia o envio.',
    expectedStages: ALL,
    expectedOutcome: { technical: 'success', business: 'approved' },
    expectedFailures: ['dados_sensiveis'],
  },
  {
    id: 'contrato_incompleto',
    nome: 'Contrato incompleto',
    grupo: 'Observabilidade',
    metodo: 'credit_card',
    descricao: 'BFF omite payment.method e session.id na autorização.',
    objetivo: 'Provar que campos obrigatórios ausentes são detectados.',
    expectedStages: ALL,
    expectedOutcome: { technical: 'success', business: 'approved' },
    expectedFailures: ['contrato.campos'],
  },
];
