apiVersion: v1
kind: ConfigMap
metadata:
  name: observability-config
data:
  DD_ENV: local-k8s
  DD_VERSION: 0.1.0
  DD_SITE: datadoghq.com
  DD_AGENT_HOST: datadog-agent
  DD_LOGS_INJECTION: "true"
  DD_TRACE_STARTUP_LOGS: "false"
  DD_TRACE_SAMPLE_RATE: "1"
  PAYMENT_URL: http://payment:8081
  ACQUIRER_URL: http://acquirer:8082
  PAYMENT_SERVICE_NAME: loja-payment-service
  ACQUIRER_SERVICE_NAME: adquirente-mock
  SLO_INICIAR_MS: "500"
  SLO_AUTORIZAR_MS: "1000"
  SLO_CONFIRMAR_MS: "500"
  ACQUIRER_TIMEOUT_MS: "2000"
