apiVersion: v1
kind: Service
metadata:
  name: bff
  labels:
    app.kubernetes.io/name: bff
spec:
  selector:
    app.kubernetes.io/name: bff
  ports:
    - name: http
      port: 8080
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    app.kubernetes.io/name: payment
spec:
  selector:
    app.kubernetes.io/name: payment
  ports:
    - name: http
      port: 8081
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: acquirer
  labels:
    app.kubernetes.io/name: acquirer
spec:
  selector:
    app.kubernetes.io/name: acquirer
  ports:
    - name: http
      port: 8082
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: dashboard
  labels:
    app.kubernetes.io/name: dashboard
spec:
  selector:
    app.kubernetes.io/name: dashboard
  ports:
    - name: http
      port: 80
      targetPort: http
